version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: forex_user
      POSTGRES_PASSWORD: forex_pass
      POSTGRES_DB: forex_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis_data:/data
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
