version: '3.8'

services:
  trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports  # Монтируем директорию отчетов
      - ./logs:/app/logs        # Монтируем логи
    restart: unless-stopped     # Автоперезапуск при падении
    networks:
      - trading-net

networks:
  trading-net:
    driver: bridge